apiVersion: v1
kind: Service
metadata:
  name: {{ include "pennyos.apiServiceName" . }}
  labels:
    {{- include "pennyos.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "pennyos.api.selectorLabels" . | nindent 4 }}
