{{- if and (not .Values.auth.existingSecret) .Values.auth.sessionSigningKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pennyos.authSecretName" . }}
  labels:
    {{- include "pennyos.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.sessionSigningKeyKey }}: {{ .Values.auth.sessionSigningKey | quote }}
{{- end }}
