{{- if and .Values.database.url (not .Values.database.urlSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pennyos.dbUrlSecretName" . }}
  labels:
    {{- include "pennyos.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "pennyos.db.urlSecretKey" . }}: {{ .Values.database.url | quote }}
{{- end }}
