{{- if and (not .Values.postgresql.enabled) (not .Values.database.passwordSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pennyos.dbSecretName" . }}
  labels:
    {{- include "pennyos.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "pennyos.db.passwordSecretKey" . }}: {{ required "database.password is required when postgresql.enabled=false and database.passwordSecret.name is empty" .Values.database.password | quote }}
{{- end }}
