{{- if and (not .Values.postgresql.enabled) (not .Values.database.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pennyos.externalDBSecretName" . }}
  labels:
    {{- include "pennyos.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.external.passwordKey }}: {{ required "database.external.password is required when postgresql.enabled=false and database.external.existingSecret is empty" .Values.database.external.password | quote }}
{{- end }}
