{{- $apiToken := and .Values.management.apiToken (not .Values.management.apiTokenSecret.name) -}}
{{- $leaseKey := and .Values.management.runtimeLeaseEncryptionKey (not .Values.management.runtimeLeaseEncryptionKeySecret.name) -}}
{{- $licenseKey := and .Values.management.runtimeAutoActivate.licenseKey (not .Values.management.runtimeAutoActivate.licenseKeySecret.name) -}}
{{- if or $apiToken $leaseKey $licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pennyos.managementSecretName" . }}
  labels:
    {{- include "pennyos.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $apiToken }}
  {{ include "pennyos.management.apiTokenSecretKey" . }}: {{ .Values.management.apiToken | quote }}
  {{- end }}
  {{- if $leaseKey }}
  {{ include "pennyos.management.runtimeLeaseEncryptionKeySecretKey" . }}: {{ .Values.management.runtimeLeaseEncryptionKey | quote }}
  {{- end }}
  {{- if $licenseKey }}
  {{ include "pennyos.management.runtimeAutoActivateLicenseKeySecretKey" . }}: {{ .Values.management.runtimeAutoActivate.licenseKey | quote }}
  {{- end }}
{{- end }}
